#%RAML 1.0 NamedExample

data:
  - id: "C152125"
    relation_type: "DEVELOPER"
    repository_user: "developer_1"
    repository_token: "ghp_WnS1O7FMQESDOT8JaXZ4Wro43JuMBbSCokLz"
  - id: "C463463"
    relation_type: "DEVELOPER"
    repository_user: "developer_2"
    repository_token: "ghp_WnS1O7FMQESDOT8JaXZ4Wro43JuMBbSCokLz"
  - id: "C737333"
    relation_type: "CUSTOMER"