#%RAML 1.0 NamedExample

- id: 1010100
  name: "Project 1"
  owner:
    id: "C10111"
    username: "sample_user"
    email_address: "sample_user@mail.com"
- id: 1010101
  name: "Project 2"
  owner:
    id: "C10111"
    username: "sample_user"
    email_address: "sample_user@mail.com"
- id: 1010102
  name: "Project 3"
  owner:
    id: "C10111"
    username: "sample_user"
    email_address: "sample_user@mail.com"
