#%RAML 1.0 NamedExample

project_id: 125111
name: "Sample project"
owner:
  id: "C23426"
  username: "sample_owner"
  email_address: "sample_owner@mail.com"
  repository_user: ""
developers:
  - id: "C245722"
    username: "sample_developer_1"
    email_address: "sample_developer_1@mail.com"
    repository_user: ""
  - id: "C245723"
    username: "sample_developer_2"
    email_address: "sample_developer_2@mail.com"
    repository_user: ""
  - id: "C245724"
    username: "sample_developer_3"
    email_address: "sample_developer_3@mail.com"
    repository_user: ""
customers:
  - id: "C245728"
    username: "sample_customer_1"
    email_address: "sample_customer_1@mail.com"
    repository_user: ""
repository: "https://github.com/organization/repository"
repository_global_user: ""
envs: []
created_at: "2024-01-16T18:35:53Z"
updated_at: "2024-01-16T22:04:49Z"